### ISSUE TITLE
Windows requirement

### ISSUE THREAD

**Issue by brkdncr** [xorangekiller/gptgen#4]
the windows build required vc_redist.x64.exe which was found here: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by xorangekiller** [comment]
Thanks for noticing this! I built those Windows binaries as a convenience for Windows users, but since I don't regularly use Windows myself, and the only Windows virtual machine that I have has Visual Studio 2019 installed so that I can compile and test open source projects (like this one) with it, I obviously already had the correct Microsoft Visual C++ Redistributable installed and didn't have any trouble running either the i386 or the x86_64 `gptgen.exe` executables that I built.

After a little trial and error, I decided to rebuild the gptgen Windows executables with the Microsoft Visual C++ Runtime statically embedded into them (rather than dynamically linked like it was before). This made them go from ~100K each to ~300K each, but it has the advantage of not requiring anyone who runs them to have the Microsoft Visual C++ Redistributable installed on their system anymore.

According to Microsoft's [/MD, /MT, /LD (Use Run-Time Library)](https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library) documentation, I had to compile gptgen with the "/MT" option (because it tells the compiler to use the multi-threaded version of the runtime library, which is apparently the static one - I don't understand how that made more sense to them than GCC's `-static` option, but whatever.) Therefore I added `-DCMAKE_CXX_FLAGS_RELEASE="/MT"` to the CMake command line, and it worked. The full build command that I ran looked something like the following:
```
cmake -G"NMake Makefiles" -DCMAKE_MAKE_PROGRAM=nmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=TRUE -DCMAKE_CXX_FLAGS_RELEASE="/MT" .
```

I replaced the [gptgen-1.2.1.zip](https://github.com/xorangekiller/gptgen/releases/download/v1.2.1/gptgen-1.2.1.zip) on the [releases page](https://github.com/xorangekiller/gptgen/releases) with a new one that contains the new static `gptgen.exe` Windows executables for both i386 and x86_64.

I believe that the new executables in the new zip file linked above solve this problem, so I am closing this issue. If they don't, please feel free to re-open it, and we can discuss what else to do about it.
